import { Inter } from "next/font/google";

// ******* Local Imports *******
import "./globals.css";
import App from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "skyimpel",
  description: "Generated by skyimpel",
  icons: {
    icon: '/assets/Union.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}
