export const SideSectionBg = '/assets/SideSectionBg.png'
export const Frame1 = '/assets/Frame1.webp'
export const Frame2 = '/assets/Frame2.webp'
export const Polygon1 = '/assets/Polygon1.svg'
export const Polygon2 = '/assets/Polygon2.svg'
export const Briefcase = '/assets/Briefcase.svg'
export const User = '/assets/User.svg'
export const ArrowRight = '/assets/ArrowRight.svg'
export const ArrowBack = '/assets/ArrowBack.svg'
export const ChevronDown = '/assets/ChevronDown.svg'
export const CircleCheckFull = '/assets/CircleCheckFull.svg'
export const GoogleIcon = '/assets/GoogleIcon.svg'
export const LockIcon = '/assets/LockIcon.svg'
export const ProfileAvatar = '/assets/ProfileAvatar.png'

